object Versions {
    const val coreKtx = "1.13.1"
    const val appcompat = "1.7.0"
    const val material = "1.12.0"
    const val activity = "1.9.2"
    const val constraintlayout = "2.1.4"
    const val junit = "4.13.2"
    const val junitest = "1.2.1"
    const val core = "3.6.1"
    const val hilt = "2.46"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutines = "1.7.3"
    const val splashScreen = "1.0.0"
    const val coil = "2.3.0"
    const val recyclerView = "1.2.1"
    const val picasso = "2.8"
}